#pragma once

// Author: Travis Johnston
// www.darkenedsoftware.com
// Date: June 4, 2008

#ifndef __POKEROMAHADEFINES_H__
#define __POKEROMAHADEFINES_H__

#include "PokerDefines.h"

namespace Omaha
{

enum class StartingHands { 
					AceAceAceAce, AceAceAceKing, AceAceAceQueen, AceAceAceJack, AceAceAceTen, AceAceAceNine, AceAceAceEight, AceAceAceSeven, AceAceAceSix, AceAceAceFive, AceAceAceFour, AceAceAceThree, AceAceAceTwo,
					AceAceKingKing, AceAceKingQueen, AceAceKingJack, AceAceKingTen, AceAceKingNine, AceAceKingEight, AceAceKingSeven, AceAceKingSix, AceAceKingFive, AceAceKingFour, AceAceKingThree, AceAceKingTwo,
					AceAceQueenQueen, AceAceQueenJack, AceAceQueenTen, AceAceQueenNine, AceAceQueenEight, AceAceQueenSeven, AceAceQueenSix, AceAceQueenFive, AceAceQueenFour, AceAceQueenThree, AceAceQueenTwo,
					AceAceJackJack, AceAceJackTen, AceAceJackNine, AceAceJackEight, AceAceJackSeven,AceAceJackSix, AceAceJackFive, AceAceJackFour, AceAceJackThree, AceAceJackTwo,
					AceAceTenTen, AceAceTenNine, AceAceTenEight, AceAceTenSeven, AceAceTenSix, AceAceTenFive, AceAceTenFour, AceAceTenThree, AceAceTenTwo,
					AceAceNineNine, AceAceNineEight, AceAceNineSeven, AceAceNineSix, AceAceNineFive, AceAceNineFour, AceAceNineThree, AceAceNineTwo,
					AceAceEightEight, AceAceEightSeven,AceAceEightSix,AceAceEightFive,AceAceEightFour,AceAceEightThree,AceAceEightTwo,
					AceAceSevenSeven,AceAceSevenSix,AceAceSevenFive,AceAceSevenFour,AceAceSevenThree,AceAceSevenTwo,
					AceAceSixSix,AceAceSixFive,AceAceSixFour,AceAceSixThree,AceAceSixTwo,
					AceAceFiveFive,AceAceFiveFour,AceAceFiveThree,AceAceFiveTwo,
					AceAceFourFour,AceAceFourThree,AceAceFourTwo,
					AceAceThreeThree,AceAceThreeTwo,
					AceAceTwoTwo,
					AceKingKingKing,AceKingKingQueen,AceKingKingJack,AceKingKingTen,AceKingKingNine,AceKingKingEight,AceKingKingSeven,AceKingKingSix,AceKingKingFive,AceKingKingFour,AceKingKingThree,AceKingKingTwo,
					AceKingQueenQueen,AceKingQueenJack,AceKingQueenTen,AceKingQueenNine,AceKingQueenEight,AceKingQueenSeven,AceKingQueenSix,AceKingQueenFive,AceKingQueenFour,AceKingQueenThree,AceKingQueenTwo,
					AceKingJackJack,AceKingJackTen,AceKingJackNine,AceKingJackEight,AceKingJackSeven,AceKingJackSix,AceKingJackFive,AceKingJackFour,AceKingJackThree,AceKingJackTwo,
					AceKingTenTen,AceKingTenNine,AceKingTenEight,AceKingTenSeven,AceKingTenSix,AceKingTenFive,AceKingTenFour,AceKingTenThree,AceKingTenTwo,
					AceKingNineNine,AceKingNineEight,AceKingNineSeven,AceKingNineSix,AceKingNineFive,AceKingNineFour,AceKingNineThree,AceKingNineTwo,
					AceKingEightEight,AceKingEightSeven,AceKingEightSix,AceKingEightFive,AceKingEightFour,AceKingEightThree,AceKingEightTwo,
					AceKingSevenSeven,AceKingSevenSix,AceKingSevenFive,AceKingSevenFour,AceKingSevenThree,AceKingSevenTwo,
					AceKingSixSix,AceKingSixFive,AceKingSixFour,AceKingSixThree,AceKingSixTwo,AceKingFiveFive,AceKingFiveFour,AceKingFiveThree,AceKingFiveTwo,
					AceKingFourFour,AceKingFourThree,AceKingFourTwo,
					AceKingThreeThree,AceKingThreeTwo,
					AceKingTwoTwo,
					AceQueenQueenQueen,AceQueenQueenJack,AceQueenQueenTen,AceQueenQueenNine,AceQueenQueenEight,AceQueenQueenSeven,AceQueenQueenSix,AceQueenQueenFive,AceQueenQueenFour,AceQueenQueenThree,AceQueenQueenTwo,
					AceQueenJackJack,AceQueenJackTen,AceQueenJackNine,AceQueenJackEight,AceQueenJackSeven,AceQueenJackSix,AceQueenJackFive,AceQueenJackFour,AceQueenJackThree,AceQueenJackTwo,
					AceQueenTenTen,AceQueenTenNine,AceQueenTenEight,AceQueenTenSeven,AceQueenTenSix,AceQueenTenFive,AceQueenTenFour,AceQueenTenThree,AceQueenTenTwo,
					AceQueenNineNine,AceQueenNineEight,AceQueenNineSeven,AceQueenNineSix,AceQueenNineFive,AceQueenNineFour,AceQueenNineThree,AceQueenNineTwo,
					AceQueenEightEight,AceQueenEightSeven,AceQueenEightSix,AceQueenEightFive,AceQueenEightFour,AceQueenEightThree,AceQueenEightTwo,
					AceQueenSevenSeven,AceQueenSevenSix,AceQueenSevenFive,AceQueenSevenFour,AceQueenSevenThree,AceQueenSevenTwo,
					AceQueenSixSix,AceQueenSixFive,AceQueenSixFour,AceQueenSixThree,AceQueenSixTwo,
					AceQueenFiveFive,AceQueenFiveFour,AceQueenFiveThree,AceQueenFiveTwo,
					AceQueenFourFour,AceQueenFourThree,AceQueenFourTwo,
					AceQueenThreeThree,AceQueenThreeTwo,
					AceQueenTwoTwo,
					AceJackJackJack,AceJackJackTen,AceJackJackNine,AceJackJackEight,AceJackJackSeven,AceJackJackSix,AceJackJackFive,AceJackJackFour,AceJackJackThree,AceJackJackTwo,
					AceJackTenTen,AceJackTenNine,AceJackTenEight,AceJackTenSeven,AceJackTenSix,AceJackTenFive,AceJackTenFour,AceJackTenThree,AceJackTenTwo,
					AceJackNineNine,AceJackNineEight,AceJackNineSeven,AceJackNineSix,AceJackNineFive,AceJackNineFour,AceJackNineThree,AceJackNineTwo,
					AceJackEightEight,AceJackEightSeven,AceJackEightSix,AceJackEightFive,AceJackEightFour,AceJackEightThree,AceJackEightTwo,
					AceJackSevenSeven,AceJackSevenSix,AceJackSevenFive,AceJackSevenFour,AceJackSevenThree,AceJackSevenTwo,
					AceJackSixSix,AceJackSixFive,AceJackSixFour,AceJackSixThree,AceJackSixTwo,
					AceJackFiveFive,AceJackFiveFour,AceJackFiveThree,AceJackFiveTwo,
					AceJackFourFour,AceJackFourThree,AceJackFourTwo,
					AceJackThreeThree,AceJackThreeTwo,
					AceJackTwoTwo,
					AceTenTenTen,AceTenTenNine,AceTenTenEight,AceTenTenSeven,AceTenTenSix,AceTenTenFive,AceTenTenFour,AceTenTenThree,AceTenTenTwo,
					AceTenNineNine,AceTenNineEight,AceTenNineSeven,AceTenNineSix,AceTenNineFive,AceTenNineFour,AceTenNineThree,AceTenNineTwo,
					AceTenEightEight,AceTenEightSeven,AceTenEightSix,AceTenEightFive,AceTenEightFour,AceTenEightThree,AceTenEightTwo,
					AceTenSevenSeven,AceTenSevenSix,AceTenSevenFive,AceTenSevenFour,AceTenSevenThree,AceTenSevenTwo,
					AceTenSixSix,AceTenSixFive,AceTenSixFour,AceTenSixThree,AceTenSixTwo,
					AceTenFiveFive,AceTenFiveFour,AceTenFiveThree,AceTenFiveTwo,
					AceTenFourFour,AceTenFourThree,AceTenFourTwo,
					AceTenThreeThree,AceTenThreeTwo,
					AceTenTwoTwo,
					AceNineNineNine,AceNineNineEight,AceNineNineSeven,AceNineNineSix,AceNineNineFive,AceNineNineFour,AceNineNineThree,AceNineNineTwo,
					AceNineEightEight,AceNineEightSeven,AceNineEightSix,AceNineEightFive,AceNineEightFour,AceNineEightThree,AceNineEightTwo,
					AceNineSevenSeven,AceNineSevenSix,AceNineSevenFive,AceNineSevenFour,AceNineSevenThree,AceNineSevenTwo,
					AceNineSixSix,AceNineSixFive,AceNineSixFour,AceNineSixThree,AceNineSixTwo,
					AceNineFiveFive,AceNineFiveFour,AceNineFiveThree,AceNineFiveTwo,
					AceNineFourFour,AceNineFourThree,AceNineFourTwo,
					AceNineThreeThree,AceNineThreeTwo,
					AceNineTwoTwo,
					AceEightEightEight,AceEightEightSeven,AceEightEightSix,AceEightEightFive,AceEightEightFour,AceEightEightThree,AceEightEightTwo,
					AceEightSevenSeven,AceEightSevenSix,AceEightSevenFive,AceEightSevenFour,AceEightSevenThree,AceEightSevenTwo,
					AceEightSixSix,AceEightSixFive,AceEightSixFour,AceEightSixThree,AceEightSixTwo,
					AceEightFiveFive,AceEightFiveFour,AceEightFiveThree,AceEightFiveTwo,
					AceEightFourFour,AceEightFourThree,AceEightFourTwo,
					AceEightThreeThree,AceEightThreeTwo,
					AceEightTwoTwo,
					AceSevenSevenSeven,AceSevenSevenSix,AceSevenSevenFive,AceSevenSevenFour,AceSevenSevenThree,AceSevenSevenTwo,
					AceSevenSixSix,AceSevenSixFive,AceSevenSixFour,AceSevenSixThree,AceSevenSixTwo,
					AceSevenFiveFive,AceSevenFiveFour,AceSevenFiveThree,AceSevenFiveTwo,
					AceSevenFourFour,AceSevenFourThree,AceSevenFourTwo,
					AceSevenThreeThree,AceSevenThreeTwo,
					AceSevenTwoTwo,
					AceSixSixSix,AceSixSixFive,AceSixSixFour,AceSixSixThree,AceSixSixTwo,
					AceSixFiveFive,AceSixFiveFour,AceSixFiveThree,AceSixFiveTwo,
					AceSixFourFour,AceSixFourThree,AceSixFourTwo,
					AceSixThreeThree,AceSixThreeTwo,
					AceSixTwoTwo,
					AceFiveFiveFive,AceFiveFiveFour,AceFiveFiveThree,AceFiveFiveTwo,
					AceFiveFourFour,AceFiveFourThree,AceFiveFourTwo,
					AceFiveThreeThree,AceFiveThreeTwo,
					AceFiveTwoTwo,
					AceFourFourFour,AceFourFourThree,AceFourFourTwo,
					AceFourThreeThree,AceFourThreeTwo,
					AceFourTwoTwo,
					AceThreeThreeThree,AceThreeThreeTwo,
					AceThreeTwoTwo,
					AceTwoTwoTwo,
					KingKingKingKing,KingKingKingQueen,KingKingKingJack,KingKingKingTen,KingKingKingNine,KingKingKingEight,KingKingKingSeven,KingKingKingSix,KingKingKingFive,KingKingKingFour,KingKingKingThree,KingKingKingTwo,
					KingKingQueenQueen,KingKingQueenJack,KingKingQueenTen,KingKingQueenNine,KingKingQueenEight,KingKingQueenSeven,KingKingQueenSix,KingKingQueenFive,KingKingQueenFour,KingKingQueenThree,KingKingQueenTwo,
					KingKingJackJack,KingKingJackTen,KingKingJackNine,KingKingJackEight,KingKingJackSeven,KingKingJackSix,KingKingJackFive,KingKingJackFour,KingKingJackThree,KingKingJackTwo,
					KingKingTenTen,KingKingTenNine,KingKingTenEight,KingKingTenSeven,KingKingTenSix,KingKingTenFive,KingKingTenFour,KingKingTenThree,KingKingTenTwo,
					KingKingNineNine,KingKingNineEight,KingKingNineSeven,KingKingNineSix,KingKingNineFive,KingKingNineFour,KingKingNineThree,KingKingNineTwo,
					KingKingEightEight,KingKingEightSeven,KingKingEightSix,KingKingEightFive,KingKingEightFour,KingKingEightThree,KingKingEightTwo,
					KingKingSevenSeven,KingKingSevenSix,KingKingSevenFive,KingKingSevenFour,KingKingSevenThree,KingKingSevenTwo,
					KingKingSixSix,KingKingSixFive,KingKingSixFour,KingKingSixThree,KingKingSixTwo,
					KingKingFiveFive,KingKingFiveFour,KingKingFiveThree,KingKingFiveTwo,
					KingKingFourFour,KingKingFourThree,KingKingFourTwo,
					KingKingThreeThree,KingKingThreeTwo,
					KingKingTwoTwo,
					KingQueenQueenQueen,KingQueenQueenJack,KingQueenQueenTen,KingQueenQueenNine,KingQueenQueenEight,KingQueenQueenSeven,KingQueenQueenSix,KingQueenQueenFive,KingQueenQueenFour,KingQueenQueenThree,KingQueenQueenTwo,
					KingQueenJackJack,KingQueenJackTen,KingQueenJackNine,KingQueenJackEight,KingQueenJackSeven,KingQueenJackSix,KingQueenJackFive,KingQueenJackFour,KingQueenJackThree,KingQueenJackTwo,
					KingQueenTenTen,KingQueenTenNine,KingQueenTenEight,KingQueenTenSeven,KingQueenTenSix,KingQueenTenFive,KingQueenTenFour,KingQueenTenThree,KingQueenTenTwo,
					KingQueenNineNine,KingQueenNineEight,KingQueenNineSeven,KingQueenNineSix,KingQueenNineFive,KingQueenNineFour,KingQueenNineThree,KingQueenNineTwo,
					KingQueenEightEight,KingQueenEightSeven,KingQueenEightSix,KingQueenEightFive,KingQueenEightFour,KingQueenEightThree,KingQueenEightTwo,
					KingQueenSevenSeven,KingQueenSevenSix,KingQueenSevenFive,KingQueenSevenFour,KingQueenSevenThree,KingQueenSevenTwo,
					KingQueenSixSix,KingQueenSixFive,KingQueenSixFour,KingQueenSixThree,KingQueenSixTwo,
					KingQueenFiveFive,KingQueenFiveFour,KingQueenFiveThree,KingQueenFiveTwo,
					KingQueenFourFour,KingQueenFourThree,KingQueenFourTwo,
					KingQueenThreeThree,KingQueenThreeTwo,
					KingQueenTwoTwo,
					KingJackJackJack,KingJackJackTen,KingJackJackNine,KingJackJackEight,KingJackJackSeven,KingJackJackSix,KingJackJackFive,KingJackJackFour,KingJackJackThree,KingJackJackTwo,
					KingJackTenTen,KingJackTenNine,KingJackTenEight,KingJackTenSeven,KingJackTenSix,KingJackTenFive,KingJackTenFour,KingJackTenThree,KingJackTenTwo,
					KingJackNineNine,KingJackNineEight,KingJackNineSeven,KingJackNineSix,KingJackNineFive,KingJackNineFour,KingJackNineThree,KingJackNineTwo,
					KingJackEightEight,KingJackEightSeven,KingJackEightSix,KingJackEightFive,KingJackEightFour,KingJackEightThree,KingJackEightTwo,
					KingJackSevenSeven,KingJackSevenSix,KingJackSevenFive,KingJackSevenFour,KingJackSevenThree,KingJackSevenTwo,
					KingJackSixSix,KingJackSixFive,KingJackSixFour,KingJackSixThree,KingJackSixTwo,
					KingJackFiveFive,KingJackFiveFour,KingJackFiveThree,KingJackFiveTwo,
					KingJackFourFour,KingJackFourThree,KingJackFourTwo,
					KingJackThreeThree,KingJackThreeTwo,
					KingJackTwoTwo,
					KingTenTenTen,KingTenTenNine,KingTenTenEight,KingTenTenSeven,KingTenTenSix,KingTenTenFive,KingTenTenFour,KingTenTenThree,KingTenTenTwo,
					KingTenNineNine,KingTenNineEight,KingTenNineSeven,KingTenNineSix,KingTenNineFive,KingTenNineFour,KingTenNineThree,KingTenNineTwo,
					KingTenEightEight,KingTenEightSeven,KingTenEightSix,KingTenEightFive,KingTenEightFour,KingTenEightThree,KingTenEightTwo,
					KingTenSevenSeven,KingTenSevenSix,KingTenSevenFive,KingTenSevenFour,KingTenSevenThree,KingTenSevenTwo,
					KingTenSixSix,KingTenSixFive,KingTenSixFour,KingTenSixThree,KingTenSixTwo,
					KingTenFiveFive,KingTenFiveFour,KingTenFiveThree,KingTenFiveTwo,
					KingTenFourFour,KingTenFourThree,KingTenFourTwo,
					KingTenThreeThree,KingTenThreeTwo,
					KingTenTwoTwo,
					KingNineNineNine,KingNineNineEight,KingNineNineSeven,KingNineNineSix,KingNineNineFive,KingNineNineFour,KingNineNineThree,KingNineNineTwo,
					KingNineEightEight,KingNineEightSeven,KingNineEightSix,KingNineEightFive,KingNineEightFour,KingNineEightThree,KingNineEightTwo,
					KingNineSevenSeven,KingNineSevenSix,KingNineSevenFive,KingNineSevenFour,KingNineSevenThree,KingNineSevenTwo,
					KingNineSixSix,KingNineSixFive,KingNineSixFour,KingNineSixThree,KingNineSixTwo,
					KingNineFiveFive,KingNineFiveFour,KingNineFiveThree,KingNineFiveTwo,
					KingNineFourFour,KingNineFourThree,KingNineFourTwo,
					KingNineThreeThree,KingNineThreeTwo,
					KingNineTwoTwo,
					KingEightEightEight,KingEightEightSeven,KingEightEightSix,KingEightEightFive,KingEightEightFour,KingEightEightThree,KingEightEightTwo,
					KingEightSevenSeven,KingEightSevenSix,KingEightSevenFive,KingEightSevenFour,KingEightSevenThree,KingEightSevenTwo,
					KingEightSixSix,KingEightSixFive,KingEightSixFour,KingEightSixThree,KingEightSixTwo,
					KingEightFiveFive,KingEightFiveFour,KingEightFiveThree,KingEightFiveTwo,
					KingEightFourFour,KingEightFourThree,KingEightFourTwo,
					KingEightThreeThree,KingEightThreeTwo,
					KingEightTwoTwo,
					KingSevenSevenSeven,KingSevenSevenSix,KingSevenSevenFive,KingSevenSevenFour,KingSevenSevenThree,KingSevenSevenTwo,
					KingSevenSixSix,KingSevenSixFive,KingSevenSixFour,KingSevenSixThree,KingSevenSixTwo,
					KingSevenFiveFive,KingSevenFiveFour,KingSevenFiveThree,KingSevenFiveTwo,
					KingSevenFourFour,KingSevenFourThree,KingSevenFourTwo,
					KingSevenThreeThree,KingSevenThreeTwo,
					KingSevenTwoTwo,
					KingSixSixSix,KingSixSixFive,KingSixSixFour,KingSixSixThree,KingSixSixTwo,
					KingSixFiveFive,KingSixFiveFour,KingSixFiveThree,KingSixFiveTwo,
					KingSixFourFour,KingSixFourThree,KingSixFourTwo,
					KingSixThreeThree,KingSixThreeTwo,
					KingSixTwoTwo,
					KingFiveFiveFive,KingFiveFiveFour,KingFiveFiveThree,KingFiveFiveTwo,
					KingFiveFourFour,KingFiveFourThree,KingFiveFourTwo,
					KingFiveThreeThree,KingFiveThreeTwo,
					KingFiveTwoTwo,
					KingFourFourFour,KingFourFourThree,KingFourFourTwo,
					KingFourThreeThree,KingFourThreeTwo,
					KingFourTwoTwo,
					KingThreeThreeThree,KingThreeThreeTwo,
					KingThreeTwoTwo,
					KingTwoTwoTwo,
					QueenQueenQueenQueen,QueenQueenQueenJack,QueenQueenQueenTen,QueenQueenQueenNine,QueenQueenQueenEight,QueenQueenQueenSeven,QueenQueenQueenSix,QueenQueenQueenFive,QueenQueenQueenFour,QueenQueenQueenThree,QueenQueenQueenTwo,
					QueenQueenJackJack,QueenQueenJackTen,QueenQueenJackNine,QueenQueenJackEight,QueenQueenJackSeven,QueenQueenJackSix,QueenQueenJackFive,QueenQueenJackFour,QueenQueenJackThree,QueenQueenJackTwo,
					QueenQueenTenTen,QueenQueenTenNine,QueenQueenTenEight,QueenQueenTenSeven,QueenQueenTenSix,QueenQueenTenFive,QueenQueenTenFour,QueenQueenTenThree,QueenQueenTenTwo,
					QueenQueenNineNine,QueenQueenNineEight,QueenQueenNineSeven,QueenQueenNineSix,QueenQueenNineFive,QueenQueenNineFour,QueenQueenNineThree,QueenQueenNineTwo,
					QueenQueenEightEight,QueenQueenEightSeven,QueenQueenEightSix,QueenQueenEightFive,QueenQueenEightFour,QueenQueenEightThree,QueenQueenEightTwo,
					QueenQueenSevenSeven,QueenQueenSevenSix,QueenQueenSevenFive,QueenQueenSevenFour,QueenQueenSevenThree,QueenQueenSevenTwo,
					QueenQueenSixSix,QueenQueenSixFive,QueenQueenSixFour,QueenQueenSixThree,QueenQueenSixTwo,
					QueenQueenFiveFive,QueenQueenFiveFour,QueenQueenFiveThree,QueenQueenFiveTwo,
					QueenQueenFourFour,QueenQueenFourThree,QueenQueenFourTwo,
					QueenQueenThreeThree,QueenQueenThreeTwo,
					QueenQueenTwoTwo,
					QueenJackJackJack,QueenJackJackTen,QueenJackJackNine,QueenJackJackEight,QueenJackJackSeven,QueenJackJackSix,QueenJackJackFive,QueenJackJackFour,QueenJackJackThree,QueenJackJackTwo,
					QueenJackTenTen,QueenJackTenNine,QueenJackTenEight,QueenJackTenSeven,QueenJackTenSix,QueenJackTenFive,QueenJackTenFour,QueenJackTenThree,QueenJackTenTwo,
					QueenJackNineNine,QueenJackNineEight,QueenJackNineSeven,QueenJackNineSix,QueenJackNineFive,QueenJackNineFour,QueenJackNineThree,QueenJackNineTwo,
					QueenJackEightEight,QueenJackEightSeven,QueenJackEightSix,QueenJackEightFive,QueenJackEightFour,QueenJackEightThree,QueenJackEightTwo,
					QueenJackSevenSeven,QueenJackSevenSix,QueenJackSevenFive,QueenJackSevenFour,QueenJackSevenThree,QueenJackSevenTwo,
					QueenJackSixSix,QueenJackSixFive,QueenJackSixFour,QueenJackSixThree,QueenJackSixTwo,
					QueenJackFiveFive,QueenJackFiveFour,QueenJackFiveThree,QueenJackFiveTwo,
					QueenJackFourFour,QueenJackFourThree,QueenJackFourTwo,
					QueenJackThreeThree,QueenJackThreeTwo,
					QueenJackTwoTwo,
					QueenTenTenTen,QueenTenTenNine,QueenTenTenEight,QueenTenTenSeven,QueenTenTenSix,QueenTenTenFive,QueenTenTenFour,QueenTenTenThree,QueenTenTenTwo,
					QueenTenNineNine,QueenTenNineEight,QueenTenNineSeven,QueenTenNineSix,QueenTenNineFive,QueenTenNineFour,QueenTenNineThree,QueenTenNineTwo,
					QueenTenEightEight,QueenTenEightSeven,QueenTenEightSix,QueenTenEightFive,QueenTenEightFour,QueenTenEightThree,QueenTenEightTwo,
					QueenTenSevenSeven,QueenTenSevenSix,QueenTenSevenFive,QueenTenSevenFour,QueenTenSevenThree,QueenTenSevenTwo,
					QueenTenSixSix,QueenTenSixFive,QueenTenSixFour,QueenTenSixThree,QueenTenSixTwo,
					QueenTenFiveFive,QueenTenFiveFour,QueenTenFiveThree,QueenTenFiveTwo,
					QueenTenFourFour,QueenTenFourThree,QueenTenFourTwo,
					QueenTenThreeThree,QueenTenThreeTwo,
					QueenTenTwoTwo,
					QueenNineNineNine,QueenNineNineEight,QueenNineNineSeven,QueenNineNineSix,QueenNineNineFive,QueenNineNineFour,QueenNineNineThree,QueenNineNineTwo,
					QueenNineEightEight,QueenNineEightSeven,QueenNineEightSix,QueenNineEightFive,QueenNineEightFour,QueenNineEightThree,QueenNineEightTwo,
					QueenNineSevenSeven,QueenNineSevenSix,QueenNineSevenFive,QueenNineSevenFour,QueenNineSevenThree,QueenNineSevenTwo,
					QueenNineSixSix,QueenNineSixFive,QueenNineSixFour,QueenNineSixThree,QueenNineSixTwo,
					QueenNineFiveFive,QueenNineFiveFour,QueenNineFiveThree,QueenNineFiveTwo,
					QueenNineFourFour,QueenNineFourThree,QueenNineFourTwo,
					QueenNineThreeThree,QueenNineThreeTwo,
					QueenNineTwoTwo,
					QueenEightEightEight,QueenEightEightSeven,QueenEightEightSix,QueenEightEightFive,QueenEightEightFour,QueenEightEightThree,QueenEightEightTwo,
					QueenEightSevenSeven,QueenEightSevenSix,QueenEightSevenFive,QueenEightSevenFour,QueenEightSevenThree,QueenEightSevenTwo,
					QueenEightSixSix,QueenEightSixFive,QueenEightSixFour,QueenEightSixThree,QueenEightSixTwo,
					QueenEightFiveFive,QueenEightFiveFour,QueenEightFiveThree,QueenEightFiveTwo,
					QueenEightFourFour,QueenEightFourThree,QueenEightFourTwo,
					QueenEightThreeThree,QueenEightThreeTwo,
					QueenEightTwoTwo,
					QueenSevenSevenSeven,QueenSevenSevenSix,QueenSevenSevenFive,QueenSevenSevenFour,QueenSevenSevenThree,QueenSevenSevenTwo,
					QueenSevenSixSix,QueenSevenSixFive,QueenSevenSixFour,QueenSevenSixThree,QueenSevenSixTwo,
					QueenSevenFiveFive,QueenSevenFiveFour,QueenSevenFiveThree,QueenSevenFiveTwo,
					QueenSevenFourFour,QueenSevenFourThree,QueenSevenFourTwo,
					QueenSevenThreeThree,QueenSevenThreeTwo,
					QueenSevenTwoTwo,
					QueenSixSixSix,QueenSixSixFive,QueenSixSixFour,QueenSixSixThree,QueenSixSixTwo,
					QueenSixFiveFive,QueenSixFiveFour,QueenSixFiveThree,QueenSixFiveTwo,
					QueenSixFourFour,QueenSixFourThree,QueenSixFourTwo,
					QueenSixThreeThree,QueenSixThreeTwo,
					QueenSixTwoTwo,
					QueenFiveFiveFive,QueenFiveFiveFour,QueenFiveFiveThree,QueenFiveFiveTwo,
					QueenFiveFourFour,QueenFiveFourThree,QueenFiveFourTwo,
					QueenFiveThreeThree,QueenFiveThreeTwo,
					QueenFiveTwoTwo,
					QueenFourFourFour,QueenFourFourThree,QueenFourFourTwo,
					QueenFourThreeThree,QueenFourThreeTwo,
					QueenFourTwoTwo,
					QueenThreeThreeThree,QueenThreeThreeTwo,
					QueenThreeTwoTwo,
					QueenTwoTwoTwo,
					JackJackJackJack,JackJackJackTen,JackJackJackNine,JackJackJackEight,JackJackJackSeven,JackJackJackSix,JackJackJackFive,JackJackJackFour,JackJackJackThree,JackJackJackTwo,
					JackJackTenTen,JackJackTenNine,JackJackTenEight,JackJackTenSeven,JackJackTenSix,JackJackTenFive,JackJackTenFour,JackJackTenThree,JackJackTenTwo,
					JackJackNineNine,JackJackNineEight,JackJackNineSeven,JackJackNineSix,JackJackNineFive,JackJackNineFour,JackJackNineThree,JackJackNineTwo,
					JackJackEightEight,JackJackEightSeven,JackJackEightSix,JackJackEightFive,JackJackEightFour,JackJackEightThree,JackJackEightTwo,
					JackJackSevenSeven,JackJackSevenSix,JackJackSevenFive,JackJackSevenFour,JackJackSevenThree,JackJackSevenTwo,
					JackJackSixSix,JackJackSixFive,JackJackSixFour,JackJackSixThree,JackJackSixTwo,
					JackJackFiveFive,JackJackFiveFour,JackJackFiveThree,JackJackFiveTwo,
					JackJackFourFour,JackJackFourThree,JackJackFourTwo,
					JackJackThreeThree,JackJackThreeTwo,
					JackJackTwoTwo,
					JackTenTenTen,JackTenTenNine,JackTenTenEight,JackTenTenSeven,JackTenTenSix,JackTenTenFive,JackTenTenFour,JackTenTenThree,JackTenTenTwo,
					JackTenNineNine,JackTenNineEight,JackTenNineSeven,JackTenNineSix,JackTenNineFive,JackTenNineFour,JackTenNineThree,JackTenNineTwo,
					JackTenEightEight,JackTenEightSeven,JackTenEightSix,JackTenEightFive,JackTenEightFour,JackTenEightThree,JackTenEightTwo,
					JackTenSevenSeven,JackTenSevenSix,JackTenSevenFive,JackTenSevenFour,JackTenSevenThree,JackTenSevenTwo,
					JackTenSixSix,JackTenSixFive,JackTenSixFour,JackTenSixThree,JackTenSixTwo,
					JackTenFiveFive,JackTenFiveFour,JackTenFiveThree,JackTenFiveTwo,
					JackTenFourFour,JackTenFourThree,JackTenFourTwo,
					JackTenThreeThree,JackTenThreeTwo,
					JackTenTwoTwo,
					JackNineNineNine,JackNineNineEight,JackNineNineSeven,JackNineNineSix,JackNineNineFive,JackNineNineFour,JackNineNineThree,JackNineNineTwo,
					JackNineEightEight,JackNineEightSeven,JackNineEightSix,JackNineEightFive,JackNineEightFour,JackNineEightThree,JackNineEightTwo,
					JackNineSevenSeven,JackNineSevenSix,JackNineSevenFive,JackNineSevenFour,JackNineSevenThree,JackNineSevenTwo,
					JackNineSixSix,JackNineSixFive,JackNineSixFour,JackNineSixThree,JackNineSixTwo,
					JackNineFiveFive,JackNineFiveFour,JackNineFiveThree,JackNineFiveTwo,
					JackNineFourFour,JackNineFourThree,JackNineFourTwo,
					JackNineThreeThree,JackNineThreeTwo,
					JackNineTwoTwo,
					JackEightEightEight,JackEightEightSeven,JackEightEightSix,JackEightEightFive,JackEightEightFour,JackEightEightThree,JackEightEightTwo,
					JackEightSevenSeven,JackEightSevenSix,JackEightSevenFive,JackEightSevenFour,JackEightSevenThree,JackEightSevenTwo,
					JackEightSixSix,JackEightSixFive,JackEightSixFour,JackEightSixThree,JackEightSixTwo,
					JackEightFiveFive,JackEightFiveFour,JackEightFiveThree,JackEightFiveTwo,
					JackEightFourFour,JackEightFourThree,JackEightFourTwo,
					JackEightThreeThree,JackEightThreeTwo,
					JackEightTwoTwo,
					JackSevenSevenSeven,JackSevenSevenSix,JackSevenSevenFive,JackSevenSevenFour,JackSevenSevenThree,JackSevenSevenTwo,
					JackSevenSixSix,JackSevenSixFive,JackSevenSixFour,JackSevenSixThree,JackSevenSixTwo,
					JackSevenFiveFive,JackSevenFiveFour,JackSevenFiveThree,JackSevenFiveTwo,
					JackSevenFourFour,JackSevenFourThree,JackSevenFourTwo,
					JackSevenThreeThree,JackSevenThreeTwo,
					JackSevenTwoTwo,
					JackSixSixSix,JackSixSixFive,JackSixSixFour,JackSixSixThree,JackSixSixTwo,
					JackSixFiveFive,JackSixFiveFour,JackSixFiveThree,JackSixFiveTwo,
					JackSixFourFour,JackSixFourThree,JackSixFourTwo,
					JackSixThreeThree,JackSixThreeTwo,
					JackSixTwoTwo,
					JackFiveFiveFive,JackFiveFiveFour,JackFiveFiveThree,JackFiveFiveTwo,
					JackFiveFourFour,JackFiveFourThree,JackFiveFourTwo,
					JackFiveThreeThree,JackFiveThreeTwo,
					JackFiveTwoTwo,
					JackFourFourFour,JackFourFourThree,JackFourFourTwo,
					JackFourThreeThree,JackFourThreeTwo,
					JackFourTwoTwo,
					JackThreeThreeThree,JackThreeThreeTwo,
					JackThreeTwoTwo,
					JackTwoTwoTwo,
					TenTenTenTen,TenTenTenNine,TenTenTenEight,TenTenTenSeven,TenTenTenSix,TenTenTenFive,TenTenTenFour,TenTenTenThree,TenTenTenTwo,
					TenTenNineNine,TenTenNineEight,TenTenNineSeven,TenTenNineSix,TenTenNineFive,TenTenNineFour,TenTenNineThree,TenTenNineTwo,
					TenTenEightEight,TenTenEightSeven,TenTenEightSix,TenTenEightFive,TenTenEightFour,TenTenEightThree,TenTenEightTwo,
					TenTenSevenSeven,TenTenSevenSix,TenTenSevenFive,TenTenSevenFour,TenTenSevenThree,TenTenSevenTwo,
					TenTenSixSix,TenTenSixFive,TenTenSixFour,TenTenSixThree,TenTenSixTwo,
					TenTenFiveFive,TenTenFiveFour,TenTenFiveThree,TenTenFiveTwo,
					TenTenFourFour,TenTenFourThree,TenTenFourTwo,
					TenTenThreeThree,TenTenThreeTwo,
					TenTenTwoTwo,
					TenNineNineNine,TenNineNineEight,TenNineNineSeven,TenNineNineSix,TenNineNineFive,TenNineNineFour,TenNineNineThree,TenNineNineTwo,
					TenNineEightEight,TenNineEightSeven,TenNineEightSix,TenNineEightFive,TenNineEightFour,TenNineEightThree,TenNineEightTwo,
					TenNineSevenSeven,TenNineSevenSix,TenNineSevenFive,TenNineSevenFour,TenNineSevenThree,TenNineSevenTwo,
					TenNineSixSix,TenNineSixFive,TenNineSixFour,TenNineSixThree,TenNineSixTwo,
					TenNineFiveFive,TenNineFiveFour,TenNineFiveThree,TenNineFiveTwo,
					TenNineFourFour,TenNineFourThree,TenNineFourTwo,
					TenNineThreeThree,TenNineThreeTwo,
					TenNineTwoTwo,
					TenEightEightEight,TenEightEightSeven,TenEightEightSix,TenEightEightFive,TenEightEightFour,TenEightEightThree,TenEightEightTwo,
					TenEightSevenSeven,TenEightSevenSix,TenEightSevenFive,TenEightSevenFour,TenEightSevenThree,TenEightSevenTwo,
					TenEightSixSix,TenEightSixFive,TenEightSixFour,TenEightSixThree,TenEightSixTwo,
					TenEightFiveFive,TenEightFiveFour,TenEightFiveThree,TenEightFiveTwo,
					TenEightFourFour,TenEightFourThree,TenEightFourTwo,
					TenEightThreeThree,TenEightThreeTwo,
					TenEightTwoTwo,
					TenSevenSevenSeven,TenSevenSevenSix,TenSevenSevenFive,TenSevenSevenFour,TenSevenSevenThree,TenSevenSevenTwo,
					TenSevenSixSix,TenSevenSixFive,TenSevenSixFour,TenSevenSixThree,TenSevenSixTwo,
					TenSevenFiveFive,TenSevenFiveFour,TenSevenFiveThree,TenSevenFiveTwo,
					TenSevenFourFour,TenSevenFourThree,TenSevenFourTwo,
					TenSevenThreeThree,TenSevenThreeTwo,
					TenSevenTwoTwo,
					TenSixSixSix,TenSixSixFive,TenSixSixFour,TenSixSixThree,TenSixSixTwo,
					TenSixFiveFive,TenSixFiveFour,TenSixFiveThree,TenSixFiveTwo,
					TenSixFourFour,TenSixFourThree,TenSixFourTwo,
					TenSixThreeThree,TenSixThreeTwo,
					TenSixTwoTwo,
					TenFiveFiveFive,TenFiveFiveFour,TenFiveFiveThree,TenFiveFiveTwo,
					TenFiveFourFour,TenFiveFourThree,TenFiveFourTwo,
					TenFiveThreeThree,TenFiveThreeTwo,
					TenFiveTwoTwo,
					TenFourFourFour,TenFourFourThree,TenFourFourTwo,
					TenFourThreeThree,TenFourThreeTwo,
					TenFourTwoTwo,
					TenThreeThreeThree,TenThreeThreeTwo,
					TenThreeTwoTwo,
					TenTwoTwoTwo,
					NineNineNineNine,NineNineNineEight,NineNineNineSeven,NineNineNineSix,NineNineNineFive,NineNineNineFour,NineNineNineThree,NineNineNineTwo,
					NineNineEightEight,NineNineEightSeven,NineNineEightSix,NineNineEightFive,NineNineEightFour,NineNineEightThree,NineNineEightTwo,
					NineNineSevenSeven,NineNineSevenSix,NineNineSevenFive,NineNineSevenFour,NineNineSevenThree,NineNineSevenTwo,
					NineNineSixSix,NineNineSixFive,NineNineSixFour,NineNineSixThree,NineNineSixTwo,
					NineNineFiveFive,NineNineFiveFour,NineNineFiveThree,NineNineFiveTwo,
					NineNineFourFour,NineNineFourThree,NineNineFourTwo,
					NineNineThreeThree,NineNineThreeTwo,
					NineNineTwoTwo,
					NineEightEightEight,NineEightEightSeven,NineEightEightSix,NineEightEightFive,NineEightEightFour,NineEightEightThree,NineEightEightTwo,
					NineEightSevenSeven,NineEightSevenSix,NineEightSevenFive,NineEightSevenFour,NineEightSevenThree,NineEightSevenTwo,
					NineEightSixSix,NineEightSixFive,NineEightSixFour,NineEightSixThree,NineEightSixTwo,
					NineEightFiveFive,NineEightFiveFour,NineEightFiveThree,NineEightFiveTwo,
					NineEightFourFour,NineEightFourThree,NineEightFourTwo,
					NineEightThreeThree,NineEightThreeTwo,NineEightTwoTwo,
					NineSevenSevenSeven,NineSevenSevenSix,NineSevenSevenFive,NineSevenSevenFour,NineSevenSevenThree,NineSevenSevenTwo,
					NineSevenSixSix,NineSevenSixFive,NineSevenSixFour,NineSevenSixThree,NineSevenSixTwo,
					NineSevenFiveFive,NineSevenFiveFour,NineSevenFiveThree,NineSevenFiveTwo,
					NineSevenFourFour,NineSevenFourThree,NineSevenFourTwo,
					NineSevenThreeThree,NineSevenThreeTwo,
					NineSevenTwoTwo,
					NineSixSixSix,NineSixSixFive,NineSixSixFour,NineSixSixThree,NineSixSixTwo,
					NineSixFiveFive,NineSixFiveFour,NineSixFiveThree,NineSixFiveTwo,
					NineSixFourFour,NineSixFourThree,NineSixFourTwo,
					NineSixThreeThree,NineSixThreeTwo,
					NineSixTwoTwo,
					NineFiveFiveFive,NineFiveFiveFour,NineFiveFiveThree,NineFiveFiveTwo,
					NineFiveFourFour,NineFiveFourThree,NineFiveFourTwo,
					NineFiveThreeThree,NineFiveThreeTwo,
					NineFiveTwoTwo,
					NineFourFourFour,NineFourFourThree,NineFourFourTwo,
					NineFourThreeThree,NineFourThreeTwo,
					NineFourTwoTwo,
					NineThreeThreeThree,NineThreeThreeTwo,NineThreeTwoTwo,
					NineTwoTwoTwo,EightEightEightEight,EightEightEightSeven,EightEightEightSix,EightEightEightFive,EightEightEightFour,EightEightEightThree,EightEightEightTwo,
					EightEightSevenSeven,EightEightSevenSix,EightEightSevenFive,EightEightSevenFour,EightEightSevenThree,EightEightSevenTwo,
					EightEightSixSix,EightEightSixFive,EightEightSixFour,EightEightSixThree,EightEightSixTwo,
					EightEightFiveFive,EightEightFiveFour,EightEightFiveThree,EightEightFiveTwo,
					EightEightFourFour,EightEightFourThree,EightEightFourTwo,
					EightEightThreeThree,EightEightThreeTwo,
					EightEightTwoTwo,
					EightSevenSevenSeven,EightSevenSevenSix,EightSevenSevenFive,EightSevenSevenFour,EightSevenSevenThree,EightSevenSevenTwo,
					EightSevenSixSix,EightSevenSixFive,EightSevenSixFour,EightSevenSixThree,EightSevenSixTwo,
					EightSevenFiveFive,EightSevenFiveFour,EightSevenFiveThree,EightSevenFiveTwo,
					EightSevenFourFour,EightSevenFourThree,EightSevenFourTwo,
					EightSevenThreeThree,EightSevenThreeTwo,
					EightSevenTwoTwo,
					EightSixSixSix,EightSixSixFive,EightSixSixFour,EightSixSixThree,EightSixSixTwo,
					EightSixFiveFive,EightSixFiveFour,EightSixFiveThree,EightSixFiveTwo,
					EightSixFourFour,EightSixFourThree,EightSixFourTwo,
					EightSixThreeThree,EightSixThreeTwo,
					EightSixTwoTwo,
					EightFiveFiveFive,EightFiveFiveFour,EightFiveFiveThree,EightFiveFiveTwo,
					EightFiveFourFour,EightFiveFourThree,EightFiveFourTwo,
					EightFiveThreeThree,EightFiveThreeTwo,
					EightFiveTwoTwo,
					EightFourFourFour,EightFourFourThree,EightFourFourTwo,
					EightFourThreeThree,EightFourThreeTwo,
					EightFourTwoTwo,
					EightThreeThreeThree,EightThreeThreeTwo,
					EightThreeTwoTwo,
					EightTwoTwoTwo,
					SevenSevenSevenSeven,SevenSevenSevenSix,SevenSevenSevenFive,SevenSevenSevenFour,SevenSevenSevenThree,SevenSevenSevenTwo,
					SevenSevenSixSix,SevenSevenSixFive,SevenSevenSixFour,SevenSevenSixThree,SevenSevenSixTwo,
					SevenSevenFiveFive,SevenSevenFiveFour,SevenSevenFiveThree,SevenSevenFiveTwo,
					SevenSevenFourFour,SevenSevenFourThree,SevenSevenFourTwo,
					SevenSevenThreeThree,SevenSevenThreeTwo,
					SevenSevenTwoTwo,
					SevenSixSixSix, SevenSixSixFive,SevenSixSixFour,SevenSixSixThree,SevenSixSixTwo,
					SevenSixFiveFive,SevenSixFiveFour,SevenSixFiveThree,SevenSixFiveTwo,
					SevenSixFourFour,SevenSixFourThree,SevenSixFourTwo,
					SevenSixThreeThree,SevenSixThreeTwo,
					SevenSixTwoTwo,
					SevenFiveFiveFive,SevenFiveFiveFour,SevenFiveFiveThree,SevenFiveFiveTwo,
					SevenFiveFourFour,SevenFiveFourThree,SevenFiveFourTwo,
					SevenFiveThreeThree,SevenFiveThreeTwo,
					SevenFiveTwoTwo,
					SevenFourFourFour,SevenFourFourThree,SevenFourFourTwo,
					SevenFourThreeThree,SevenFourThreeTwo,
					SevenFourTwoTwo,
					SevenThreeThreeThree,SevenThreeThreeTwo,
					SevenThreeTwoTwo,
					SevenTwoTwoTwo,
					SixSixSixSix,SixSixSixFive,SixSixSixFour,SixSixSixThree,SixSixSixTwo,
					SixSixFiveFive,SixSixFiveFour,SixSixFiveThree,SixSixFiveTwo,
					SixSixFourFour,SixSixFourThree,SixSixFourTwo,
					SixSixThreeThree,SixSixThreeTwo,
					SixSixTwoTwo,
					SixFiveFiveFive,SixFiveFiveFour,SixFiveFiveThree,SixFiveFiveTwo,
					SixFiveFourFour,SixFiveFourThree,SixFiveFourTwo,
					SixFiveThreeThree,SixFiveThreeTwo,
					SixFiveTwoTwo,
					SixFourFourFour,SixFourFourThree,SixFourFourTwo,
					SixFourThreeThree,SixFourThreeTwo,
					SixFourTwoTwo,
					SixThreeThreeThree,SixThreeThreeTwo,
					SixThreeTwoTwo,
					SixTwoTwoTwo,
					FiveFiveFiveFive,FiveFiveFiveFour,FiveFiveFiveThree,FiveFiveFiveTwo,
					FiveFiveFourFour,FiveFiveFourThree,FiveFiveFourTwo,
					FiveFiveThreeThree,FiveFiveThreeTwo,
					FiveFiveTwoTwo,
					FiveFourFourFour,FiveFourFourThree,FiveFourFourTwo,
					FiveFourThreeThree,FiveFourThreeTwo,
					FiveFourTwoTwo,
					FiveThreeThreeThree,FiveThreeThreeTwo,
					FiveThreeTwoTwo,
					FiveTwoTwoTwo,
					FourFourFourFour,FourFourFourThree,FourFourFourTwo,
					FourFourThreeThree,FourFourThreeTwo,
					FourFourTwoTwo,
					FourThreeThreeThree,FourThreeThreeTwo,
					FourThreeTwoTwo,
					FourTwoTwoTwo,
					ThreeThreeThreeThree,ThreeThreeThreeTwo,
					ThreeThreeTwoTwo,ThreeTwoTwoTwo,
					TwoTwoTwoTwo,
					Max
			};


template < typename type > class Pocket
{
public:
	type mPocket[4];
	bool operator==( const Pocket & pocket );
	Pocket(){mPocket[0] = type::Max;mPocket[1] = type::Max;mPocket[2] = type::Max;mPocket[3] = type::Max;}
};

template <typename type > bool Pocket<type>::operator==( const Pocket & pocket )
{
	assert(mPocket[0] != type::Max);
	assert(mPocket[1] != type::Max);
	assert(mPocket[2] != type::Max);
	assert(mPocket[3] != type::Max);
	assert(pocket.mPocket[0] != type::Max);
	assert(pocket.mPocket[1] != type::Max);
	assert(pocket.mPocket[3] != type::Max);
	assert(pocket.mPocket[4] != type::Max);

	if(  mPocket[0] == pocket.mPocket[0] && mPocket[1] == pocket.mPocket[1] && mPocket[2] == pocket.mPocket[2] && mPocket[3] == pocket.mPocket[3])
		return true;
	return false;
}

typedef Pocket<Cards> HoleCards;
typedef Pocket<Ranks> HoleCardRanks;
typedef Pocket<Suits> HoleCardSuits;

bool RanksFromStartingHand( StartingHands hand, HoleCardRanks ranks );
bool CardsFromStartingHand( StartingHands hand, HoleCards & cards );

} // End of namespace Omaha

#endif // __POKEROMAHADEFINES_H__

